(function(action, event, CONFIG) {
  const H = {
    Envios:["submission_id","folio","timestamp","campaign","organization","person_id","quality_impact","client_timezone","client_submitted_at"],
    Personas:["person_id","employee_id","full_name","category","created_at"],
    Respuestas:["response_id","submission_id","section_id","question_id","question_number","score"],
    Comentarios:["comment_id","submission_id","section_id","type","text","created_at"],
    Seguimiento:["followup_id","submission_id","followup_category","followup_type","priority","status","notes","updated_at"],
    Log:["timestamp","event","detail"]
  };
  const N={submissions:"Envios",people:"Personas",responses:"Respuestas",comments:"Comentarios",followups:"Seguimiento",log:"Log"};
  function out(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
  function clean(v,n){return String(v||"").trim().slice(0,n||1200)}
  function sh(ss,n){let s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);if(!s.getLastRow()){s.getRange(1,1,1,H[n].length).setValues([H[n]]).setFontWeight("bold").setBackground("#092756").setFontColor("#fff");s.setFrozenRows(1)}else if(n==="Envios"&&s.getRange(1,1,1,s.getLastColumn()).getValues()[0].indexOf("folio")<0){s.insertColumnAfter(1);s.getRange(1,2).setValue("folio").setFontWeight("bold").setBackground("#092756").setFontColor("#fff")}return s}
  function rows(s){if(!s||s.getLastRow()<2)return[];let v=s.getDataRange().getValues(),h=v.shift();return v.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])))}
  function normalized(v){return clean(v,160).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9 ]/g," ").replace(/\s+/g," ").trim()}
  function initials(fullName){let p=normalized(fullName).split(" ").filter(Boolean);if(p.length>=3)return p.slice(2).map(x=>x[0]).join("")+p[0][0]+p[1][0];return p.map(x=>x[0]).join("")||"SINID"}
  function validate(b){if(!b.person||!clean(b.person.fullName))throw Error("El nombre es obligatorio.");let eid=normalized(b.person.employeeId).replace(/ /g,"");if(eid&&!/^ITC\d{5}$/.test(eid))throw Error("El ID debe tener el formato ITC06190.");if(!clean(b.person.category))throw Error("La categoría es obligatoria.");if(!Array.isArray(b.responses)||b.responses.length!==25)throw Error("Se esperaban 25 respuestas.");b.responses.forEach(r=>{if(![1,2,3].includes(Number(r.score)))throw Error("Respuesta fuera de escala.")});if(!["Sí","No","Parcialmente"].includes(b.qualityImpact))throw Error("Falta la respuesta sobre calidad.");if((b.qualityImpact==="Sí"||b.qualityImpact==="Parcialmente")&&!clean(b.qualityDetail))throw Error("Explica cómo afecta la calidad.");if(!clean(b.improvements))throw Error("Indica una propuesta de mejora.")}
  function save(b){let l=LockService.getScriptLock();l.waitLock(20000);try{let ss=SpreadsheetApp.openById(CONFIG.SHEET_ID),d=new Date(),sid=Utilities.getUuid(),pid=Utilities.getUuid(),eid=normalized(b.person.employeeId).replace(/ /g,""),name=clean(b.person.fullName,160),nameKey=normalized(name),ps=sh(ss,N.people),es=sh(ss,N.submissions),people=rows(ps),subs=rows(es),activePeople=new Set(subs.map(x=>String(x.person_id))),duplicate=people.find(p=>activePeople.has(String(p.person_id))&&((eid&&normalized(p.employee_id).replace(/ /g,"")===eid)||normalized(p.full_name)===nameKey));if(duplicate)throw Error("Ya existe una respuesta registrada para este ID o nombre completo. La encuesta solo puede responderse una vez por persona.");let personCode=eid||initials(name),folio=`ITC-FMT-SI-026-01-${personCode}-1`;ps.appendRow([pid,eid,name,clean(b.person.category,80),d]);es.appendRow([sid,folio,d,clean(b.campaign,30),clean(b.organization,120),pid,b.qualityImpact,clean(b.client&&b.client.timezone,80),clean(b.client&&b.client.submittedAt,40)]);let rr=b.responses.map(r=>[Utilities.getUuid(),sid,clean(r.sectionId,10),clean(r.questionId,20),Number(r.questionNumber),Number(r.score)]),rs=sh(ss,N.responses);rs.getRange(rs.getLastRow()+1,1,rr.length,6).setValues(rr);let notes=(b.notes||[]).concat([{sectionId:"S4",type:"general",text:b.generalNote},{sectionId:"S5",type:"impacto_calidad",text:b.qualityDetail},{sectionId:"S5",type:"mejora",text:b.improvements}]).filter(x=>clean(x.text));if(notes.length){let cr=notes.map(x=>[Utilities.getUuid(),sid,clean(x.sectionId,10),clean(x.type,40),clean(x.text),d]),cs=sh(ss,N.comments);cs.getRange(cs.getLastRow()+1,1,cr.length,6).setValues(cr)}return{submissionId:sid,folio}}finally{l.releaseLock()}}
  function recommendation(sub,allResponses){let rs=allResponses.filter(r=>r.submission_id===sub.submission_id),groups={};rs.forEach(r=>(groups[r.section_id]=groups[r.section_id]||[]).push(Number(r.score)));let sectionMap={S1:"Condiciones físicas",S2:"Relaciones laborales",S3:"Organización y carga de trabajo",S4:"Evaluación general"},sections=Object.keys(groups).map(k=>({sectionId:k,category:sectionMap[k]||k,effectiveness:groups[k].reduce((a,b)=>a+b,0)/(groups[k].length*3)*100})),overall=rs.length?rs.reduce((a,r)=>a+Number(r.score),0)/(rs.length*3)*100:null,worst=sections.slice().sort((a,b)=>a.effectiveness-b.effectiveness)[0],deficient=sections.filter(x=>x.effectiveness<70),regular=sections.filter(x=>x.effectiveness>=70&&x.effectiveness<85),impact=sub.quality_impact||"No",needs=!!deficient.length||!!regular.length||impact!=="No",type=deficient.length?"Acción correctiva inmediata":regular.length?"Plan de mejora a mediano plazo":impact!=="No"?"Revisión de impacto en calidad":"Seguimiento periódico",priority=deficient.length||impact==="Sí"?"Alta":regular.length||impact==="Parcialmente"?"Media":"Baja",cats=(deficient.length?deficient:regular.length?regular:impact!=="No"?[{category:"Impacto en calidad"}]:[{category:"Seguimiento periódico"}]).map(x=>x.category);return{requiresFollowup:needs,followupType:type,priority,autoCategory:cats[0],recommendedCategories:cats,overallEffectiveness:overall,sectionResults:sections,reason:needs?`${type}. ${cats.join(", ")}.`:"Resultado excelente; únicamente seguimiento periódico."}}
  function adminRecords(){let ss=SpreadsheetApp.openById(CONFIG.SHEET_ID),subs=rows(ss.getSheetByName(N.submissions)),people=rows(ss.getSheetByName(N.people)),responses=rows(ss.getSheetByName(N.responses)),followups=rows(ss.getSheetByName(N.followups)),pm=Object.fromEntries(people.map(x=>[x.person_id,x])),fm=Object.fromEntries(followups.map(x=>[x.submission_id,x]));return subs.slice().reverse().map(x=>{let p=pm[x.person_id]||{},f=fm[x.submission_id]||{},auto=recommendation(x,responses),overridden=!!f.followup_id,requires=overridden?f.status!=="No requiere":auto.requiresFollowup;return{submissionId:x.submission_id,folio:x.folio||"",timestamp:x.timestamp,employeeId:p.employee_id||"",fullName:p.full_name||"",category:p.category||"",campaign:x.campaign||"",requiresFollowup:requires,automatic:!overridden,followupCategory:f.followup_category||auto.autoCategory,followupType:f.followup_type||auto.followupType,priority:f.priority||auto.priority,status:f.status||(auto.requiresFollowup?"Pendiente":"No requiere"),notes:f.notes||"",updatedAt:f.updated_at||"",recommendedCategories:auto.recommendedCategories,overallEffectiveness:auto.overallEffectiveness,sectionResults:auto.sectionResults,reason:overridden&&f.status==="No requiere"?"Clasificación administrativa: no requiere seguimiento.":auto.reason}})}
  function saveFollowup(b){let allowedCategories=["Condiciones físicas","Relaciones laborales","Organización y carga de trabajo","Evaluación general","Impacto en calidad","Seguimiento periódico","Equipo y herramientas","Seguridad","Capacitación","Otro"],allowedTypes=["Acción correctiva inmediata","Plan de mejora a mediano plazo","Revisión de impacto en calidad","Seguimiento periódico"],allowedPriorities=["Alta","Media","Baja"],allowedStatuses=["Pendiente","En proceso","Atendido","Cerrado","No requiere"],sid=clean(b.submissionId,80),cat=clean(b.followupCategory,80),type=clean(b.followupType,80),priority=clean(b.priority,20),status=clean(b.status,30),notes=clean(b.notes,1200);if(!sid)throw Error("Falta el registro de referencia.");if(!allowedCategories.includes(cat)||!allowedTypes.includes(type))throw Error("Clasificación de seguimiento no válida.");if(!allowedPriorities.includes(priority)||!allowedStatuses.includes(status))throw Error("Prioridad o estado no válido.");let l=LockService.getScriptLock();l.waitLock(20000);try{let ss=SpreadsheetApp.openById(CONFIG.SHEET_ID),fs=sh(ss,N.followups),v=fs.getDataRange().getValues(),h=v.shift(),sidIx=h.indexOf("submission_id"),row=v.findIndex(r=>String(r[sidIx])===sid),record=[row>=0?v[row][0]:Utilities.getUuid(),sid,cat,type,priority,status,notes,new Date()];if(row>=0)fs.getRange(row+2,1,1,record.length).setValues([record]);else fs.appendRow(record);return{saved:true}}finally{l.releaseLock()}}
  function deleteSubmission(sid){sid=clean(sid,80);if(!sid)throw Error("Falta el identificador del registro.");let l=LockService.getScriptLock();l.waitLock(20000);try{let ss=SpreadsheetApp.openById(CONFIG.SHEET_ID),removed=0;[N.submissions,N.responses,N.comments,N.followups].forEach(n=>{let s=ss.getSheetByName(n);if(!s||s.getLastRow()<2)return;let v=s.getDataRange().getValues(),h=v.shift(),ix=h.indexOf("submission_id");if(ix<0)return;for(let i=v.length-1;i>=0;i--)if(String(v[i][ix])===sid){s.deleteRow(i+2);removed++}});let es=ss.getSheetByName(N.submissions),ps=ss.getSheetByName(N.people);if(es&&ps&&ps.getLastRow()>=2){let ev=es.getDataRange().getValues(),eh=ev.shift(),pidIx=eh.indexOf("person_id"),remaining=new Set(ev.map(r=>String(r[pidIx]))),pv=ps.getDataRange().getValues(),ph=pv.shift(),idIx=ph.indexOf("person_id");for(let i=pv.length-1;i>=0;i--)if(!remaining.has(String(pv[i][idIx])))ps.deleteRow(i+2)}if(removed){let lg=sh(ss,N.log);lg.appendRow([new Date(),"delete_submission",sid])}return{removed:removed>0}}finally{l.releaseLock()}}
  function report(p){let ss=SpreadsheetApp.openById(CONFIG.SHEET_ID),subs=rows(ss.getSheetByName(N.submissions)),people=rows(ss.getSheetByName(N.people)),resp=rows(ss.getSheetByName(N.responses)),com=rows(ss.getSheetByName(N.comments)),followups=rows(ss.getSheetByName(N.followups)),pm=Object.fromEntries(people.map(x=>[x.person_id,x])),fm=Object.fromEntries(followups.map(x=>[x.submission_id,x])),campaigns=[...new Set(subs.map(x=>String(x.campaign)))].sort(),categories=[...new Set(people.map(x=>String(x.category)))].sort(),selected=subs.filter(x=>(!p.campaign||String(x.campaign)===p.campaign)&&(!p.category||String((pm[x.person_id]||{}).category)===p.category)),sm=Object.fromEntries(selected.map(x=>[x.submission_id,x])),ids=new Set(selected.map(x=>x.submission_id)),filtered=resp.filter(x=>ids.has(x.submission_id));function agg(a,k){let m={};a.forEach(x=>(m[x[k]]=m[x[k]]||[]).push(Number(x.score)));return Object.keys(m).map(z=>({key:z,average:m[z].reduce((a,b)=>a+b,0)/m[z].length,effectiveness:m[z].reduce((a,b)=>a+b,0)/(m[z].length*3)*100}))}let overall=filtered.length?filtered.reduce((a,x)=>a+Number(x.score),0)/(filtered.length*3)*100:null,byCat=categories.map(c=>{let sids=new Set(selected.filter(x=>(pm[x.person_id]||{}).category===c).map(x=>x.submission_id)),r=filtered.filter(x=>sids.has(x.submission_id));return{category:c,submissions:sids.size,effectiveness:r.length?r.reduce((a,x)=>a+Number(x.score),0)/(r.length*3)*100:0}}).filter(x=>x.submissions);return{ok:true,generatedAt:new Date().toISOString(),filters:{campaigns,categories},summary:{submissions:selected.length,effectiveness:overall,impactPercent:selected.length?selected.filter(x=>x.quality_impact!=="No").length/selected.length*100:null},sections:agg(filtered,"section_id").map(x=>({sectionId:x.key,effectiveness:x.effectiveness})),categories:byCat,questions:agg(filtered,"question_id").map(x=>{let z=filtered.find(r=>r.question_id===x.key)||{};return{questionId:x.key,questionNumber:Number(z.question_number),average:x.average,effectiveness:x.effectiveness}}),comments:com.filter(x=>ids.has(x.submission_id)).slice(-200).reverse().map(x=>{let s=sm[x.submission_id]||{},person=pm[s.person_id]||{},rec=recommendation(s,resp),f=fm[x.submission_id]||{},overridden=!!f.followup_id;return{timestamp:x.created_at,fullName:person.full_name||"",employeeId:person.employee_id||"",category:person.category||"",type:x.type,text:x.text,requiresFollowup:overridden?f.status!=="No requiere":rec.requiresFollowup,followupType:f.followup_type||rec.followupType}})}}
  try{
    if(action==="init"){let ss=SpreadsheetApp.openById(CONFIG.SHEET_ID);Object.keys(H).forEach(n=>sh(ss,n));return true}
    if(action==="post"){let b=JSON.parse(event.postData.contents||"{}");if(b.action==="delete"){if(b.key!==CONFIG.ADMIN_KEY)return out({ok:false,error:"Clave incorrecta."});return out({ok:true,...deleteSubmission(b.submissionId)})}if(b.action==="followup"){if(b.key!==CONFIG.ADMIN_KEY)return out({ok:false,error:"Clave incorrecta."});return out({ok:true,...saveFollowup(b)})}if(b.action!=="submit"||b.token!==CONFIG.WRITE_TOKEN)return out({ok:false,error:"Solicitud no autorizada."});validate(b);let saved=save(b);return out({ok:true,submissionId:saved.submissionId,folio:saved.folio})}
    if(action==="get"){if(String(event.parameter.key||"")!==CONFIG.ADMIN_KEY)return out({ok:false,error:"Clave incorrecta."});if(String(event.parameter.view||"")==="records")return out({ok:true,records:adminRecords()});return out(report(event.parameter))}
  }catch(err){return out({ok:false,error:String(err.message||err)})}
})
 
